apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-k3-app
  namespace: go-k3-app-ns
  labels:
    app: go-k3-app
    version: v1.0.0
    tier: backend
  annotations:
    description: "Deployment for the go-k3 application"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-k3-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: go-k3-app
        version: v1.0.0
        tier: backend
    spec:
      containers:
        - name: go-k3-app
          image: go-k3-app:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
