apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: go-k3-app-ns
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'go-k3-app'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - go-k3-app-ns
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            regex: go-k3-app
            action: keep
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            regex: metrics
            action: keep
          - source_labels: [__meta_kubernetes_namespace]
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_service_name]
            target_label: kubernetes_service