apiVersion: v1
kind: Service
metadata:
  name: go-k3-app-service
  namespace: my-namespace
  annotations:
    description: "Service to expose go-k3-app using a LoadBalancer"
spec:
  selector:
    app: go-k3-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  sessionAffinity: None
