apiVersion: v1
kind: Service
metadata:
  name: go-k3-app-service
  namespace: go-k3-app-ns
  labels:
    app: go-k3-app 
spec:
  type: LoadBalancer
  selector:
    app: go-k3-app
  ports:
    - port: 80
      targetPort: 8080
      name: metrics
